name: "pull-requests"

on:
  pull_request:
    types: [opened, edited, reopend]

jobs:
  if_merged:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "The PR is opened"
