name: "staging-image"

on:
  pull_request:
    types: 
      - closed
jobs:
  staging-image-creation:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "staging image has been created"
